### ISSUE TITLE
Issues with Path

### ISSUE THREAD

**Issue by DDReaper** [roy-t/AStar#1]
Great library and love the lack of dependencies.  However, it doesn't seem to sort on best path, or could just be the viewer maybe?

![image](https://user-images.githubusercontent.com/1793042/28942237-821ab24e-7892-11e7-90e0-c27f3590b2aa.png)

As you can see, it's clearly marking a path which is not "best".

Any thoughts?

**Comment by roy-t** [comment]
Hey Simon,

Wow that looks extremely wrong. The search time is also huge. I'll try to replicate this problem asap and I'll see if I can fix it!

**Comment by roy-t** [comment]
I've found the bug and fixed it.
![fix](https://user-images.githubusercontent.com/623634/28963088-25b84b94-7908-11e7-8241-7a9c3cdfcf48.PNG)

I store the data of the grid in a 1D array, I did not always compute the index into that array correctly (`dimx * x + y` instead of `dimx * y + x`) at one place. I've made sure this cannot happen again. I've also tweaked the distance metric. Since the squared Euclidian distance metric I used actually overestimates the cost of getting somewhere. Which also resulted in sometimes slightly sub-optimal paths. I now use the Chebyshev distance metric. 

I've uploaded the changes to the repository. I'll publish a new NuGet package at the end of the day, once I'm home. Thanks so much for reporting this problem!

**Comment by DDReaper** [comment]
Thanks for catching it.  Will do some more testing
At least it's best to find it early and then double down on Unit Tests :D

**Comment by roy-t** [comment]
I'll open a new issue for unit tests. Its definitely needed. But I'm having a hard time thinking of where/how to add them.

**Comment by roy-t** [comment]
The updated nuget package was release and is available at https://www.nuget.org/packages/RoyT.AStar/
