### ISSUE TITLE
Memory allocation number is unacceptable and library author ignoring the concerns

### ISSUE THREAD

**Issue by aienabled** [roy-t/AStar#24]
Hello!

There is an excessive amount of allocations and I'm surprised the author is saying there are no allocations and even closing the issue without any explanation #9...
Basically, any request to find a path results in _at least_ a single List, single Stack, and single Array allocations (effectively multiplying the amount of memory traffic and GC pressure).
I cannot see any collection pools used to reduce the number of allocations, and in some cases, there are excessive collections allocated and data is copied, which could be easily avoided.

For example:
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/PathFinder.cs#L19
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/PathFinder.cs#L26
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/PathFinder.cs#L132

Why not use Array.Empty<Position> here?
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/Grid.cs#L126

Here a Stack is created just to reverse the List, then it's converted to an Array. I find this code extremely confusing as there are obvious approaches how to reverse-copy list content into an Array without using an intermediate Stack object, or avoiding allocating both Stack and Array altogether as the List entries could be reversed in a single for loop right inside the List and then the List object itself could be returned (though the result type should be `IReadOnlyList<Position>` in that case which is usually fine):
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/Grid.cs#L131
https://github.com/roy-t/AStar/blob/8a3c6acb82fb0434bb10892156b1bbdcb66b41c1/Roy-T.AStar/Grid.cs#L138

And that just a few obvious cases which I've found on the highest API level by quickly reading the code of the `Grid` and `Pathfinding` classes.

I hope the author is willing to improve these moments (especially the most obvious ones). I found that the author is using BenchmarkDotNet to measure performance but I'm really surprised the allocations aspect is neglected...

It's a general rule that allocations should be minimized for games even if the game is shipped for modern .NET Framework/.NET Core instead of outdated Mono. Any GC implementation is taking precious time in the main thread and could result in noticeable hiccups for the players. Considering that pathfinding is often one of the heaviest sections of the code (which could be invoked thousands of times per second for some games such as strategy or MMOs) such amount of allocations should be avoided. Especially as modern .NET has all sorts of pooled collection approaches to ensure the best performance and often avoid the allocations altogether.

Regards!

**Comment by mikkleini** [comment]
You can DIY and create a pull request...

**Comment by roy-t** [comment]
Hey, great that you put so much work in finding the places that could be improved. I closed some old issues about a year ago because I thought nobody was interested anymore.

As I commented in #9 there are no allocations on the heap in the search algorithm. Only the utilities around it allocate. But they mostly Allocate short lived objects, that the compiler/gc can easily reason about. But these things could indeed improve. 

But I don't want to slavishly work towards less allocations unless if it is giving problems. Zero allocations, like all performance optimizations shouldn't be done prematurely. And should only be done where it matters.

Do you have any problems, what is your use case, how are you using the library?

(In my own use case I search for paths on a separate thread, long paths but only a handful per second. In this case I don't notice any problems. I can imagine that in other use cases the code might not behave so nice. We can fix that!)

**Comment by roy-t** [comment]
Closing because of no response, and I'm working on a big refactor that will probably also alleviate some of these issues.

**Comment by JoNMii** [comment]
How is the state of this issue? It is eatinng literally TONS of memory just for one 600x600 grid with only lateral movements enabled.
Thanks

**Comment by roy-t** [comment]
@JoNMii as far as I know there are no outstanding memory/performance issues with this library. But I'd be happy to improve things if someone show's me a case where the code behaves badly. As I care a lot about performance :).

I can't really do much with the comment 'TONS'. Is the memory used increasing more than you expect? For example I would expect a 600x600 grid to use 4x as much memory as a 300*300.

**Comment by brasky** [comment]
I tried to use this library as a quick implementation for something that would need to scale to thousands and I quickly realized the allocation is insane. 

If you add MemoryDiagnoser to your benchmarks you can clearly see it

```
| Method                         | Mean            | Error          | StdDev         | Gen0     | Gen1    | Allocated |
|------------------------------- |----------------:|---------------:|---------------:|---------:|--------:|----------:|
| GridBench                      |    48,119.79 ns |   1,214.707 ns |   3,524.087 ns |   2.0142 |  0.0610 |   25952 B |
| GridWithHoleBench              |        46.21 ns |       0.990 ns |       2.905 ns |   0.0089 |       - |     112 B |
| GridWithRandomHolesBench       |    26,399.39 ns |     522.346 ns |   1,231.232 ns |   1.1902 |       - |   15032 B |
| GridWithRandomLimitsBench      | 3,950,048.39 ns |  78,590.703 ns | 165,774.478 ns |  62.5000 | 15.6250 |  828675 B |
| GridWithUnreachableTargetBench | 2,551,623.40 ns |  58,205.056 ns | 167,934.906 ns |  50.7813 | 11.7188 |  670434 B |
| GridWithGradientBench          | 6,661,934.62 ns | 131,248.881 ns | 262,118.217 ns | 117.1875 | 23.4375 | 1559027 B |
```

The objects in this pathfinding are huge and a lot are created on large grids.

You can improve the time it takes to run the benchmarks by moving your setup logic out of the constructor and into a new Setup function with the [GlobalSetup] attribute by the way

**Comment by roy-t** [comment]
Hey!

Thanks for putting in the time to make these numbers more concrete. 

The grid (or actually graph) to run the GridBench benchmark has 100.000 cells and almost 800.000 edges. It still finds a path in 0.000048 seconds, which I still find mind bogglingly fast. But it indeed allocates 24kb, which sounds like it shouldn't be necessary.

I bet that is because I did some stupid things, like using a Linq query to get the maximum velocity by looking at outgoing edges from all outgoing nodes. (For a feature that honestly should not be in this library). 

There are also a lot of helper classes like GridPosition and GridSize that you could argue are unnecessary. But I really liked that explicit style when I created this library 8 years ago (I was learning about Domain Driven Design back then, and wanted to see how that would translate to games).

The library is also missing a lot of the awesome new performance enhancing features like spans and memory, since that didn't exist back then.

With the knowledge and language features there are now I would definitely write parts of this library quite differently. But I don't want to spend the time right now to make sweeping changes. I mostly keep the library working for those few happy users that send me encouraging messages once in a while. 

For your own projects I would suggest to take the code from the MinHeap and PathFinder as inspiration and to strip out everything that you don't need (like Velocity information). In an hour or two you should have a path finder that is tailored to your needs.

**Comment by brasky** [comment]
So... I realized that some of my issue was 100% not this library so I apologize for that! 

I did take some time to optimize and this is where I've got the benchmarks today (before vs after)

![Image](https://github.com/user-attachments/assets/f768588e-be15-426b-9602-99cf2702b2c6)

![Image](https://github.com/user-attachments/assets/747027e6-997e-462b-982b-4b77c3dbc414)

I'm going to clean it up, would you be open to a PR? I don't believe I've made any functionality changes, all the tests are green and I can do some more thorough testing.

**Comment by roy-t** [comment]
Hey, that's great to hear. No worries we are still learning. Those numbers look amazing. Almost suspiciously so 😅. I'm in vacation for a few days. But I would be happy to look at a PR looks like I will learn a few tricks from you.

**Comment by brasky** [comment]
Well I made some changes that involve getting rid of object allocation almost entirely, but they come at the expense of things probably looking "less organized". I will put up a PR and look forward to your review. Enjoy your vacation!
