### ISSUE TITLE
Question: GPS coordinates

### ISSUE THREAD

**Issue by Dzivo** [roy-t/AStar#43]
Is it posible to use GPS coordinates as position values since i wasnt able to make my example work.
Also is it posible to assign some ids to the nodes so that later on i can find out which node coresponds to my information about that node.

Thanks for an awsome library saved me a lot of time.

**Comment by roy-t** [comment]
Hey Dzivo, using literal GPS coordinates won't work since the positions in this library are meant to work on a flat surface. Paths are computed based on a straight line distance. For small distances, like inside a city this might work OK. But for large distances it will definitely not work. 

(Closing this right now, but feel free to re-open if you have more questions :) ).

**Comment by Dzivo** [comment]
Hi thanks for fast reply. What do you think about implementing an inteface for weight calculation and distance calculation so that we can overwrite your functionality or even adding abilty to calculate distances using `haversine` formula out of the box.
I can help by implementing this features if you are insterested.

**Comment by Dzivo** [comment]
Also another thing i think you missed is about the IDs or a way to connect graph points with some data. Is there a way to do that ?
