### ISSUE TITLE
Question : Bidirectional graph search

### ISSUE THREAD

**Issue by PascalSoftwares** [roy-t/AStar#48]
In some cases, two nodes are connected with two directional arcs that have different costs (i.e uphill / downhill).
Can this scenario be configured in your library?

**Comment by roy-t** [comment]
Hey, unfortunately not right now since the connect method on a node creates both edges. I think it could be an easy addition. Would happily accept a Pull Request.
________________________________
From: PascalSoftwares ***@***.***>
Sent: Wednesday, April 13, 2022 4:19:24 PM
To: roy-t/AStar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [roy-t/AStar] Question : Bidirectional graph search (Issue #48)


In some cases, two nodes are connected with two directional arcs that have different costs (i.e uphill / downhill).
Can this scenario be configured in your library?
