### ISSUE TITLE
Add Grid.Connect(GridPosition position)?

### ISSUE THREAD

**Issue by dch-GH** [roy-t/AStar#52]
I'm assuming I'm either :
A.) missing some obvious reason why this is not implemented in the public API like Grid.Disconnect
or
B.) not understanding how if or how Grid.AddEdge works in adding/readding walkable "valid" nodes.

**Comment by roy-t** [comment]
Hey thanks for your question.

If I understand you correctly a connect method will connect that one node to all its neighbors. That is a bit problematic since some users want only lateral connections, or only diagonal, or both. While disconnect just disconnects everything. 

I could create utility methods for connect for a few logical combinations. Just like I did for creating a grid. I just never thought about it. Do you think it would be useful to have those in the library? 

Of course you can for now implement it using AddEdge several times. Or are you running into problems there?

**Comment by dch-GH** [comment]
> Hey thanks for your question.
> 
> If I understand you correctly a connect method will connect that one node to all its neighbors. That is a bit problematic since some users want only lateral connections, or only diagonal, or both. While disconnect just disconnects everything.
> 
> I could create utility methods for connect for a few logical combinations. Just like I did for creating a grid. I just never thought about it. Do you think it would be useful to have those in the library?
> 
> Of course you can for now implement it using AddEdge several times. Or are you running into problems there?

Thank you getting back to me!

Yes, I have stumbled into understanding how to use AddEdge to *sort of* get it working. 

Feel free to tell me if this is not how I should be using AddEdge.
```cs
			var targetNode = Grid.GetNode( gridPos );
			var targetNodePosition = ToGrid( targetNode.Position );
			var neighbors = GetNeighbors( targetNode, true );

			foreach ( var n in neighbors )
			{
                                // Neighbors can be null at the edges of the map.
				if ( n is null )
					continue;

				var neighborPos = ToGrid( n.Position );
				Grid.AddEdge( targetNodePosition, neighborPos, Velocity.FromKilometersPerHour( 100 ) );
			}
```

I'm essentially trying to have the ability to tell the library that a node is not considered "walkable" and to flip that flag when I want (adding/removing obstacles). I figure Connecting/Disconnecting the Nodes I want to do that to is the idiomatic way. If such utility methods would make that easier for me, then yes I would definitely appreciate that.

**Comment by roy-t** [comment]
Ah, yes that is indeed the correct way. This comes because the actual library is based on nodes and edges, not a grid. The grid class is just an abstraction above it to help users with the common case of a grid. In this case that abstraction leaks through. Glad you have figured this out. I'll make a note of this and will see if in the next version I can make using grids more logical.
